import turtle
screen = turtle.Screen()
screen.bgcolor("white")
pen = turtle.Turtle()
pen.color((1, 1, 0))
pen.begin_fill()
pen.circle(50)
pen.end_fill()
pen.penup()
pen.goto(150, 0)
pen.pendown()
pen.color((1, 0.647, 0))
pen.begin_fill()
pen.circle(50)
pen.end_fill()
pen.hideturtle()
turtle.done()
